name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Build sdk
        working-directory: ./packages/sdk
        run: yarn build

      - name: Generate typechain
        working-directory: ./packages/contracts
        run: yarn typechain

      - name: Run Tests
        working-directory: ./packages/contracts
        run: yarn test

env:
  MNEMONIC: "we need a mnemonic phrase so that continuous integration will not fail"
  INFURA_API_KEY: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  MATICVIGIL_API_KEY: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
